### ISSUE TITLE
Lack of button support?

### ISSUE THREAD

**Issue by Toffe87** [tuomasjjrasanen/python-uinput#12]
Hi.

I love how this work but i'd love it to have more button support? Where is the limitation on this? I mean there are buttons e.g. BTN_TR, BTN_A, BTN_THUMB? 

Reason i ask is because i have made my own "controller" and want to use uinput as a driver for it, and i cant get it to act like my xbox usb controller? Mapping buttons like top left trigger e.t.c? 

Are uinput the limitation?

**Comment by tuomasjjrasanen** [comment]
Hi, this should be now fixed in master branch. The issue was fixed by commit https://github.com/tuomasjjrasanen/python-uinput/commit/7f9f4e317be3b31c17e1cf5e53df179e2ac4fe4e. Thanks for reporting!

**Comment by Toffe87** [comment]
Awesome, I've downloaded the git, ran setup.py build then install as stated and tried running my script replacing KEY_A with BTN_A and it crashes?

> Traceback (most recent call last):
>   File "i2ctest.py", line 43, in <module>
>     device = uinput.Device(events)
>   File "/usr/local/lib/python2.7/dist-packages/uinput/__init__.py", line 181, in __init__
>     _libsuinput.suinput_enable_event(self.__uinput_fd, ev_type, ev_code)
> ctypes.ArgumentError: argument 3: <type 'exceptions.TypeError'>: Don't know how to convert parameter 3
> 


Code
```
# Setup uinput device and keys
events = (
	uinput.BTN_JOYSTICK,
    uinput.ABS_X+(0,255,0,0),
    uinput.ABS_Y+(0,255,0,0),
    uinput.BTN_A,
    uinput.BTN_B,
    uinput.BTN_X,
    uinput.BTN_Y,
    uinput.BTN_TL,
    uinput.BTN_TR,
    uinput.KEY_ENTER,
    uinput.KEY_SPACE,
)

```

**Comment by Toffe87** [comment]
Also tried your code example:

> pi@retropie:~/sgp-buttons $ sudo python test.py
> Traceback (most recent call last):
>   File "test.py", line 3, in <module>
>     with uinput.Device([uinput.BTN_A, uinput.BTN_B]) as device:
>   File "/usr/local/lib/python2.7/dist-packages/uinput/__init__.py", line 181, in __init__
>     _libsuinput.suinput_enable_event(self.__uinput_fd, ev_type, ev_code)
> ctypes.ArgumentError: argument 3: <type 'exceptions.TypeError'>: Don't know how to convert parameter 3
> 

```
import uinput

with uinput.Device([uinput.BTN_A, uinput.BTN_B]) as device:
    device.emit_combo([uinput.BTN_A, uinput.BTN_B])

```

Might be me who cant install correctly? Any way to check version?

**Comment by Toffe87** [comment]
Creating a new issue, found problem, dont know how to fix (I'm a noob)
