### ISSUE TITLE
When using button A, B, X, Y uinput crashes.

### ISSUE THREAD

**Issue by Toffe87** [tuomasjjrasanen/python-uinput#13]
As stated above, 

```
BTN_SOUTH = (0x01, 0x130)
BTN_A = (0x01, BTN_SOUTH)
BTN_EAST = (0x01, 0x131)
BTN_B = (0x01, BTN_EAST)
BTN_C = (0x01, 0x132)
BTN_NORTH = (0x01, 0x133)
BTN_X = (0x01, BTN_NORTH)
BTN_WEST = (0x01, 0x134)
BTN_Y = (0x01, BTN_WEST)
BTN_Z = (0x01, 0x135)
```

Your code under init on parsing of the inputs:

 ```
       for ev_spec in self.__events:
            ev_type, ev_code = ev_spec[:2]
```

BTN_A will be (0x01, (0x01, 0x130)) which crashes the system on that line. Dont know how that is fixed, you probably do +1

**Comment by tuomasjjrasanen** [comment]
Blargh, yeah. Thanks for reporting. Could you please try now, I just made a fix. See https://github.com/tuomasjjrasanen/python-uinput/commit/89d712688ad932ede910f7cdb0859fcc1d417b10

**Comment by Toffe87** [comment]
Hi.

That would fix it, i just used SOUTH instead of A e.t.c but your fix is correct. :)

**Comment by tuomasjjrasanen** [comment]
Great, thanks again!
