### ISSUE TITLE
Can't even include library

### ISSUE THREAD

**Issue by Kitsumi** [tuomasjjrasanen/python-uinput#15]
No matter where I include the lib, it always has the same error...
Traceback (most recent call last):
  File "joystick.py", line 1, in <module>
    import uinput
  File "/usr/lib/python2.7/site-packages/uinput/__init__.py", line 42, in <module>
    _ABS_CNT = ABS_MAX[1] + 1
NameError: name 'ABS_MAX' is not defined

**Comment by caffVic** [comment]
Same problem here. I'm using Arch and tried both python 2 and 3.

**Comment by Kitsumi** [comment]
I'm using Antergos 64-Bit if that helps :P
Python 2, and Python 3 don't work.

**Comment by Kitsumi** [comment]
Its an issue with ev.py, when I checked the file after building/installing, it was empty
As a quick and dirty fix, I just placed the variables from ev.py over the 'from .ev import *' line

**Comment by caffVic** [comment]
Thx Kitsumi.
Installing from master also results on an empty ev.py. Copying ev.py from master to /usr/lib/python3.5/site-packages/uinput/ev.py also works if you wanna make it cleaner.

**Comment by Kitsumi** [comment]
Oh nice! Glad your problem was solved!

**Comment by caffVic** [comment]
So this is really a non-issue. This got solved here https://github.com/tuomasjjrasanen/python-uinput/commit/7f9f4e317be3b31c17e1cf5e53df179e2ac4fe4e

We just happened to run the old released version of the script. When I attempted installing from master I probably hadn't uninstalled the library properly.

So fixing this only requires to make a new release. Time for 0.10.3?

**Comment by tuomasjjrasanen** [comment]
Thanks for reporting and thanks for helping each other!

@caffVic This has been fixed in the latest release.
