### ISSUE TITLE
List of possible keys?

### ISSUE THREAD

**Issue by JanezCim** [tuomasjjrasanen/python-uinput#2]
Hello!
I love this library because it's very simple and easy!

But I've been searching, but haven't found any list of all the possible keys that you can emulate with it... Like is scroll possible and something like KEY_ENTER?

Thanks!

**Comment by kirbyfan64** [comment]
There's a list of buttons [here](https://github.com/torvalds/linux/blob/master/include/uapi/linux/input.h#L214).

**Comment by JanezCim** [comment]
Thanks!

**Comment by Nascar** [comment]
They have changed how they arranged the input so now it is in its own header file [here](https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h#L15).
Thanks for the original answer!
