### ISSUE TITLE
Module loaded, no errors but no keypress.

### ISSUE THREAD

**Issue by raqbit** [tuomasjjrasanen/python-uinput#20]
Running python-uinput on my pi 2B+ here, but I cannot get it to actually press keys.

uinput module is loaded, there are no errors when I run my python script, but the key isn't pressed.

Test code:
http://pastebin.com/bD3vRH6B

I'm checking for inputs using `xev`.

**Comment by ritiek** [comment]
@Raqbit I have the same problem. Does it work for you now?
