### ISSUE TITLE
 PermissionError: [Errno 13] Failed to open the uinput device: Permission denied

### ISSUE THREAD

**Issue by hasibzunair** [tuomasjjrasanen/python-uinput#25]
Getting this error when i run the example code.

**Comment by edusanketdk** [comment]
why did you close this issue?

**Comment by hasibzunair** [comment]
I totally forgot. Even forgot when I used it!

**Comment by edusanketdk** [comment]
Lol! I am facing this issue. Browsed almost every corner of internet, but couldn't resolve.

**Comment by hasibzunair** [comment]
Goodluck finding it.
