### ISSUE TITLE
Compilation Error in Ubuntu 14.04 64-bit

### ISSUE THREAD

**Issue by cgwennap** [tuomasjjrasanen/python-uinput#3]
When running the command `python setup.py build`, compiler returns an error, stating "Cannot open shared object file libudev.so".

The problem appears to be the caused by the replacement of `libudev.so` with `libudev.so.0` (older version with deprecated interface which may not exist in current `libudev` builds) and `libudev.so.1` (new version being supported) as part of its merge into `systemd`.

This error was hotfixed by replacing `"libudev.so"` in `setup.py` with `"libudev.so.1"`, but requires further testing to determine full cross-compatibility.

**Comment by kirbyfan64** [comment]
Can't `ctypes.util.find_library` be used to do this portably?

**Comment by cgwennap** [comment]
Possibly, if it's set up to do so, which it isn't currently?

**Comment by imarcleolz** [comment]
I found the same problem in Ubuntu 10.15.
But that was easily solved with the following command:

`sudo apt-get install libudev-dev`

I hope this helps!

**Comment by cgwennap** [comment]
Yep, confirmed on Ubuntu 16

**Comment by tuomasjjrasanen** [comment]
Thanks for reporting and thanks for helping each other when I was gone :).

I've made a new release, 0.11.1. This issue has been fixed there.
