### ISSUE TITLE
Project unmaintained?

### ISSUE THREAD

**Issue by gitanat** [tuomasjjrasanen/python-uinput#48]
@tuomasjjrasanen Could you please let us know if you are still maintaining this project?

There are a few good pull requests that are unmerged, and uncoordinated forks have been popping up.

I'm happy to help with project maintenance on this repo, or doing a more coordinated forking with the rest of the community.

**Comment by tuomasjjrasanen** [comment]
I'm alive, see my coment: https://github.com/tuomasjjrasanen/python-uinput/issues/49#issuecomment-1951352788
