### ISSUE TITLE
missing quotedbl

### ISSUE THREAD

**Issue by alsoeric** [tuomasjjrasanen/python-uinput#5]
I don't seem to be able to generate the "  character. The keysym "quotedbl" used by  TK  doesn't exist. I checked input.h  but I can't find it there either.

 What am I missing?

**Comment by tuomasjjrasanen** [comment]
Hi and sorry for answering probably too late..

But, in short, uinput works on keycode level, not on symbol level. The answer to the question of how to produce a certain symbol, double quotes in this case, depends on used the keyboard layout.

In my pc105 FI (Finnish) keyboard layout, double quotes are generated by key combination ``KEY_LEFTSHIFT + KEY_2``. In pc105 US (US English) keyboard, double quotes could be generated with ``KEY_LEFTSHIFT + KEY_APOSTROPHE`` .

**Comment by alsoeric** [comment]
no, no not too late. I take forever sometimes to get personal projects done. If you take a look at https://github.com/alsoeric/speechbridge  you will see how I'm taking the keysyms output from tk  and then translating it into a keycode.  I also have to deal with some insanities by NaturallySpeaking. For example, it will sometimes emit a shift code without unshifting.

Suggestions for improvement would be welcome.
