### ISSUE TITLE
Pypi package transition

### ISSUE THREAD

**Issue by gitanat** [tuomasjjrasanen/python-uinput#50]
@tuomasjjrasanen Would you like to perform the uploads of the new releases, or would you rather I do it?

If you'd like you can add me on https://pypi.org/manage/project/python-uinput/collaboration/

Another option is coordinating on importing back the changes from the python-uinput2 repo

**Comment by gitanat** [comment]
@tuomasjjrasanen Do you think you'd be able to look into this soon?

**Comment by tuomasjjrasanen** [comment]
I just invited you as a maintainer.

**Comment by gitanat** [comment]
@tuomasjjrasanen I'm sorry, I received the invite, but I was away for a few days and the link has since expired. Would you mind re-sending?

**Comment by tuomasjjrasanen** [comment]
Yep, re-sent just now.
