### ISSUE TITLE
setup.py doesn't generate ev.py correctly for latest kernels

### ISSUE THREAD

**Issue by j-m-harris** [tuomasjjrasanen/python-uinput#9]
see https://github.com/tuomasjjrasanen/python-uinput/blob/master/setup.py#L10

Path here should now be /usr/include/linux/input-event-codes.h
(since Oct 2015- https://github.com/torvalds/linux/commits/master/include/uapi/linux/input-event-codes.h)

**Comment by wkevina** [comment]
I have the same issue. Thanks @j-m-harris for pointing this out. I made a pull request that should fix this in a backwards compatible manner.

**Comment by tuomasjjrasanen** [comment]
Thanks for @j-m-harris for reporting this and @wkevina for fixing it!

**Comment by idupree** [comment]
Yay! For future people googling, here is an error message I got that I think was due to this bug:

```
Traceback (most recent call last):
  File "une.py", line 1, in <module>
    import uinput
  File "/Users/me/HOME/.local/lib/python2.7/site-packages/uinput/__init__.py", line 42, in <module>
    _ABS_CNT = ABS_MAX[1] + 1
NameError: name 'ABS_MAX' is not defined
```

**Comment by tuomasjjrasanen** [comment]
Thanks Isaac!

**Comment by j-m-harris** [comment]
@idupree agreed, that's the sort of error I was getting too.

@wkevina Thanks for writing the patch!
